### ISSUE TITLE
01 February 2023

### ISSUE THREAD

**Issue by ImSaMPro** [AIOCodeBase/LCPOTD#194]
# **Task Lists**

- [x] #195
- [x] #196
- [ ] [C] Add C Solution for Problem Of The Day
- [ ] [C#] Add C# Solution for Problem Of The Day
- [x] #197
- [ ] [JavaScript] Add JavaScript Solution for Problem Of The Day
- [x] #198
- [ ] [Python] Add Python Solution for Problem Of The Day
- [ ] [Ruby] Add Ruby Solution for Problem Of The Day
- [ ] [Rust] Add Rust Solution for Problem Of The Day
- [ ] [Swift] Add Swift Solution for Problem Of The Day
- [ ] [Go] Add Go Solution for Problem Of The Day
- [ ] [Scala] Add Scala Solution for Problem Of The Day
- [ ] [Kotlin] Add Kotlin Solution for Problem Of The Day
- [ ] [PHP] Add PHP Solution for Problem Of The Day
- [ ] [TrueScript] Add TrueScript Solution for Problem Of The Day

<br />
<br />

### **How do I get assigned to these issues?**

*You must leave a comment with the issues you want assigned.*

### **Is there any limit to the number of issues that can be assigned?**

*Yes, one person can only be assigned two issues per day from the four (README, C++, Java, and Python 3).*

### **Can I be assigned to multiple issues on different days by commenting once?**

*Yes, you can be assigned to multiple issues on different days by commenting once. However, you must be assigned to the contributor role in order to do so. If you already have access to the contributor role, simply list the issue in a comment that you want to be assigned to.*

**Example:**
```
01 January 2023 - Java & Python
04 January 2023 - README.md & Java
12 January 2023 - C++
19 January 2023 - README.md
```

### **How do I get access to the Contributor role?**

*You must contribute 2-3 times before being granted access to the contributor role.*
