### ISSUE TITLE
20 March 2023

### ISSUE THREAD

**Issue by ImSaMPro** [AIOCodeBase/LCPOTD#383]
# **Task Lists**

- [x] #431
- [ ] [C++] Add C++ Solution for Problem Of The Day
- [ ] [C] Add C Solution for Problem Of The Day
- [ ] [C#] Add C# Solution for Problem Of The Day
- [x] #432
- [ ] [JavaScript] Add JavaScript Solution for Problem Of The Day
- [ ] [Python3] Add Python3 Solution for Problem Of The Day
- [ ] [Python] Add Python Solution for Problem Of The Day
- [ ] [Ruby] Add Ruby Solution for Problem Of The Day
- [ ] [Rust] Add Rust Solution for Problem Of The Day
- [ ] [Swift] Add Swift Solution for Problem Of The Day
- [ ] [Go] Add Go Solution for Problem Of The Day
- [ ] [Scala] Add Scala Solution for Problem Of The Day
- [ ] #400
- [ ] [PHP] Add PHP Solution for Problem Of The Day
- [ ] [TrueScript] Add TrueScript Solution for Problem Of The Day

<br />
<br />

### **How do I get assigned to these issues?**

*You must leave a comment with the issues you want assigned.*

### **Is there any limit to the number of issues that can be assigned?**

*Yes, one person can only be assigned two issues per day from the four (README, C++, Java, Python3 etc).*

### **Can I be assigned to multiple issues on different days by commenting once?**

*Yes, you can be assigned to multiple issues on different days by commenting once. However, you must be assigned to the contributor role in order to do so. If you already have access to the contributor role, simply list the issue in a comment that you want to be assigned to.*

**Example:**
```
01 January 2023 - Java & Python
04 January 2023 - README.md & Java
12 January 2023 - C++
19 January 2023 - README.md
```

### **How do I get access to the Contributor role?**

*You must contribute 2-3 times before being granted access to the contributor role.*

**Comment by chiragcode11** [comment]
20 march 2023 - kotlin

**Comment by chiragcode11** [comment]
@ImSaMPro can you tell me from where I need to pick the problem of the day

**Comment by ImSaMPro** [comment]
@chiragcode11 also accept the contributor role sent in your email! So that you could be assigned or comment here: https://github.com/AIOCodeBase/LCPOTD/issues/400

**Comment by chiragcode11** [comment]
@ImSaMPro  I have accepted  the invitation

**Comment by chiragcode11** [comment]
am I assigned ?

**Comment by chiragcode11** [comment]
Do I need to write the code here or should I create a PR

**Comment by ImSaMPro** [comment]
@chiragcode11 You may write your code on your computer or on the LeetCode website, and once it has been tested on the website, you can file a PR if the application functions as intended and is error-free.

**Comment by chiragcode11** [comment]
class Solution {
    fun isCompleteTree(root: TreeNode): Boolean {
        val Q: Queue<TreeNode> = LinkedList()
        Q.offer(root)
        var flag = false
        while (!Q.isEmpty()) {
            val temp = Q.poll()
            if (temp == null) flag = true else {
                if (flag) return false
                Q.offer(temp.left)
                Q.offer(temp.right)
            }
        }
        return true
    }
}

**Comment by chiragcode11** [comment]
here is the solution code which is tested

**Comment by ImSaMPro** [comment]
> Do I need to write the code here or should I create a PR

You have to make a PR!

https://github.com/AIOCodeBase/LCPOTD/blob/main/CONTRIBUTING.md
